name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake (Dark + Correct Path)
        uses: Platane/snk@v3
        with:
          github_user_name: "DnyaneshwariBorse"
          outputs: |
            dist/snake-dark.svg?palette=github-dark
            dist/snake.svg

      - name: Upload Snake Files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: output
          commit_message: "ğŸ Update Snake Animation"
          file_pattern: dist/**
