name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"   # Runs every midnight
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake Animation (Dark Theme)
        uses: Platane/snk@v3
        with:
          github_user_name: "DnyaneshwariBorse"
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Commit Snake Files to output branch
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: output
          commit_message: "üêç Update Snake Animation"
          file_pattern: dist/**
