name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # runs every midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: "DnyaneshwariBorse"
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Push to output
        uses: EndBug/add-and-commit@v9
        with:
          message: "Generated snake animation"
          add: "dist"
          default_author: github_actions

      - name: Push output
        uses: ad-m/github-push-action@master
        with:
          branch: output
          github_token: ${{ secrets.GITHUB_TOKEN }}
